name: build
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Run the Docker container using the openjdk image. The build folder is shared so we can upload the coverage report.
        run: docker run --name ci -v $(pwd)/build:/usr/local/myapp/build -it -d openjdk:17-slim-bullseye /bin/bash
      - name: Copy the source code into the container.
        run: docker cp . ci:/usr/local/myapp
      - name: Run the build command.
        run: docker exec -w /usr/local/myapp ci ./gradlew build
      - name: Stop the container.
        run: docker stop ci
      - name: Remove the container.
        run: docker rm ci
      - name: Upload the coverage report to codecov.io.
        run: bash <(curl -s https://codecov.io/bash)
        if: success()
